# Generated by Django 4.2.6 on 2023-11-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answer_likes', to='app.like'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to='app.like'),
            preserve_default=False,
        ),
    ]
