# Generated by Django 4.2.6 on 2023-11-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_like_remove_answer_likes_remove_question_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='cnt',
            field=models.IntegerField(null=0),
        ),
    ]
