# Generated by Django 4.2.6 on 2023-11-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislike',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answer_dislikes', to='app.like'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='dislike',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='question_dislikes', to='app.like'),
            preserve_default=False,
        ),
    ]
