# Generated by Django 4.2.6 on 2023-12-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=' static/img/avatars/default.jpg', upload_to=' static/img/avatars/'),
        ),
    ]
