# Generated by Django 4.2.6 on 2023-12-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/avatars/default.jpg', upload_to='img/avatars/'),
        ),
    ]
